import Head from 'next/head'
import Layout from '../layout/Layout'
import { Section } from '../styles/GlobalComponents'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>Pheon Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-white.png" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/logo-white.png" />
        <meta
            name="keywords"
            content="web development, programming, react js, next js, react native, vue js, app development, coding, automation, python, django, firebase, node js, web, software development"
        />
      </Head>
      <Section>
        <h1>Hero</h1>
      </Section>
    </div>
    </Layout>
  )
}
